DROP TABLE IF EXISTS Addresses;
DROP TABLE IF EXISTS CODStats;
DROP TABLE IF EXISTS FortKiteStats;
DROP TABLE IF EXISTS MaddeningStats;
DROP TABLE IF EXISTS SantaAns;
DROP TABLE IF EXISTS UserGamer;
DROP TABLE IF EXISTS Users;

-- If int() stops working, use tinyint for 0-255 and smallint for larger
-- A message to myself

CREATE TABLE Users (
    UserId INT(4) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Avatar VARCHAR(100) NOT NULL,
    FirstName VARCHAR(30),
    LastName VARCHAR(30),
    Email VARCHAR(50)
);

CREATE TABLE Addresses (
    LocalId INT(4) PRIMARY KEY AUTO_INCREMENT NOT NULL, 
    IpAddress VARCHAR(15),
    Location VARCHAR(100),
    UserId INT(4) NOT NULL,
    CONSTRAINT FK_UsersAddresses FOREIGN KEY(UserId) REFERENCES Users(UserId) on UPDATE CASCADE on DELETE CASCADE
);

CREATE TABLE CODStats (
    CODId INT(4) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CODKills INT(6),
    CODTeam VARCHAR(30),
    CODWins INT(4),
    UserId INT(4) NOT NULL,
    CONSTRAINT FK_UsersCODStats FOREIGN KEY(UserId) REFERENCES Users(UserId) on UPDATE CASCADE on DELETE CASCADE
);

CREATE TABLE FortKiteStats (
    FortId INT(4) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FortKiteKills INT(6),
    FortKiteWins INT(5),
    UserId INT(4),
    CONSTRAINT FK_UsersFortKiteStats FOREIGN KEY(UserId) REFERENCES Users(UserId) on UPDATE CASCADE on DELETE CASCADE
);

CREATE TABLE MaddeningStats (
    MadId INT(4) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Mad2025Wins INT(4),
    Mad2025Losses INT(4),
    Mad2025Ties INT(2),
    Mad2025Team VARCHAR(30),
    UserId INT(4) NOT NULL,
    CONSTRAINT FK_UsersMaddeningStats FOREIGN KEY(UserId) REFERENCES Users(UserId) on UPDATE CASCADE on DELETE CASCADE
);

CREATE TABLE SantaAns (
    SantaId INT(4) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    SecretSanta CHAR(1),
    UserId INT(4) NOT NULL,
    CONSTRAINT FK_UsersSantaAns FOREIGN KEY(UserId) REFERENCES Users(UserId) on UPDATE CASCADE on DELETE CASCADE
);

CREATE TABLE UserGamer (
    GamerId INT(4) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    UserId INT(4) NOT NULL,
    Gamertag VARCHAR(25) NOT NULL,
    CONSTRAINT FK_UsersUserGamer FOREIGN KEY(UserId) REFERENCES Users(UserId) on UPDATE CASCADE on DELETE CASCADE
);

COMMIT;
